<?php
// Call UNL_Common_BuildingTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "UNL_Common_BuildingTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'UNL/Common/Building.php';

/**
 * Test class for UNL_Common_Building.
 * Generated by PHPUnit_Util_Skeleton on 2007-04-17 at 10:31:47.
 */
class UNL_Common_BuildingTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("UNL_Common_BuildingTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGetAllCodes().
     */
    public function testGetAllCodes() {
        // Remove the following line when you implement this test.
        $this->markTestIncomplete(
          "This test has not been implemented yet."
        );
    }

    /**
     * @todo Implement testBuildingExists().
     */
    public function testBuildingExists() {
		$bldgs = new UNL_Common_Building();
        $this->assertTrue($bldgs->buildingExists('501'));
        $this->assertFalse($bldgs->buildingExists('blahblah'));
    }

    /**
     * @todo Implement testGetCampus().
     */
    public function testGetCampus() {
        $bldgs = new UNL_Common_Building();
        $this->assertEquals('city',$bldgs->getCampus('501'));
        $this->assertEquals('east',$bldgs->getCampus('ECU'));
    }
}

// Call UNL_Common_BuildingTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "UNL_Common_BuildingTest::main") {
    UNL_Common_BuildingTest::main();
}
?>
